spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: storage-service-test
      client-id: storage-service-test
    listener:
      auto-startup: false

management:
  health:
    kafka:
      enabled: false

logging:
  structured:
    format:
      console: ${LOGGING_STRUCTURED_FORMAT_CONSOLE:}

cicd:
  executor:
    topic: jobs.storage
    worker-id: storage-test-worker-1

server:
  port: 0
