server:
  port: ${SERVER_PORT:8082}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:storage-service-local}
      client-id: ${KAFKA_CLIENT_ID:storage-service-local}

logging:
  structured:
    format:
      console: ${LOGGING_STRUCTURED_FORMAT_CONSOLE:}

cicd:
  executor:
    topic: ${CICD_EXECUTOR_TOPIC:jobs.storage}
    worker-id: ${CICD_WORKER_ID:storage-local-worker-1}
