server:
  port: 0

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: vcs-service-test
      client-id: vcs-service-test

management:
  health:
    kafka:
      enabled: false

cicd:
  executor:
    topic: jobs.vcs
    worker-id: vcs-test-worker-1
