spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: fuzzing-service-test
      client-id: fuzzing-service-test

management:
  health:
    kafka:
      enabled: false

logging:
  structured:
    format:
      console: ${LOGGING_STRUCTURED_FORMAT_CONSOLE:}

cicd:
  executor:
    topic: jobs.fuzzing
    worker-id: fuzzing-test-worker-1

server:
  port: 0
